### ISSUE TITLE
Testing APIs: using basic authentication

### ISSUE THREAD

**Issue by lvanvugt** [PacktPublishing/Automated-Testing-in-Microsoft-Dynamics-365-Business-Central-Second-Edition#16]
In chapter 13 is shown how to test your own APIs making use of the trick MS is using with respect to authentication as "Including the authentication in tests would be quite cumbersome" as I state in the following section (taken from chapter 13):

### Authenticating the client
The next challenge is the authentication of the client as the service being called upon will require the client’s credentials. Including the authentication in tests would be quite cumbersome, and therefore the Microsoft Business Central team has chosen the practical approach, focusing on testing the API business logic and not validating the authentication. As such API tests are run in a database with no user and user-related data. In order to achieve this, the following needs to be done:

1.	Set up your Business Central environment to use Windows authentication.
2.	Remove all user and user-related data from the database.
3.	Deploy your extension(s) with your application and test code.
4.	Run the tests with standard test runner `Test Runner - Isol. Disabled` (130451).

Note that with this approach, we ignore testing the authorization to the server.

## Trade-off
The trade-off of using Windows authentication is that it is **not** (easily) possible to get your API tests run in a pipeline as most probably the various parts of the pipeline are not run/triggered in your domain.

## Alternative trick
Triggered by my Dutch Dynamics Community presentation, and later my Areopa webinar, [Automated testing of your Business Central API](https://www.youtube.com/watch?v=xKnYtdiAG0A&t) Arend-Jan Kauffmann - who else - suggested to use the following trick allowing the usage of basic authentication. In this we are assuming we're using a docker container.

1. When building the docker container for testing the APIs the user and password are known
2. Adjust the script in such a way that it:
   a. adds an extension which introduces a table in BC - let's call it `Test Setup` - with a field in which the password can be stored
   b. populates that field with the password
3. Design your API tests to make use of this password (combined with the user)

**Comment by Arthurvdv** [comment]
Our development and our Azure DevOps pipelines environments are all setup-ed with Username/Password.

The idea is to create a small extension to have a eventsubscriber on the OnBeforeGetResponse and add BasicAuthentication to the API-call. With this maybe the standard tests of Microsoft would also be able to execute?

For now waiting for the event request here: https://github.com/microsoft/ALAppExtensions/issues/15756

**Comment by Arthurvdv** [comment]
![image](https://user-images.githubusercontent.com/44637996/168018014-010660f2-e984-4c2d-aa1a-35e16f0182c5.png)
![image](https://user-images.githubusercontent.com/44637996/168017930-8a0dc3ac-ecfd-434f-a7be-148bf2c4b6dd.png)

@lvanvugt: Good news, I have testing APIs working using basic authentication!

Adding this GraphMgtEventHandler.Codeunit.al file, that will add the credentials to the default Codeunit "Library - Graph Mgt" when executing a call.

* This event is available since Business Central 2022 release wave 1 (v20) ([link](https://github.com/microsoft/ALAppExtensions/issues/16103))
* The requirement here is that the user has created a Web Services Access Key.

```AL
codeunit 50000 "PTE Graph Mgt Event Handler"
{
    SingleInstance = true;

    var
        IdentityManagement: Codeunit "Identity Management";
        WebServicesKey: Text[80];

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Library - Graph Mgt", 'OnAfterInitializeWebRequestWithURL', '', false, false)]
    local procedure OnAfterInitializeWebRequestWithURL(var HttpWebRequestMgt: Codeunit "Http Web Request Mgt.")
    begin
        if WebServicesKey = '' then
            WebServicesKey := IdentityManagement.GetWebServicesKey(UserSecurityId());

        HttpWebRequestMgt.AddBasicAuthentication(UserId(), WebServicesKey);
    end;
}
```

**HOW-TO handle the Web Services Access Key?**
We use Docker in our CI/CD strategy, and always create a separate App for the tests. In the app.json of the Test-App we can add this parameter:
```JSON
"target": "OnPrem",
```

This makes it possible to create a Install.Codeunit.al in the Test-App that assigns every user with a Web Services Access Key 

```AL
codeunit 50000 "PTE Install"
{
    Subtype = Install;

    trigger OnInstallAppPerCompany()
    begin
        VerifyWebServicesKeyPerUser();
    end;

    local procedure VerifyWebServicesKeyPerUser()
    var
        User: Record User;
        IdentityManagement: Codeunit "Identity Management";
    begin
        User.SetLoadFields("User Security ID");
        if User.FindSet() then
            repeat
                if IdentityManagement.GetWebServicesKey(User."User Security ID") = '' then
                    IdentityManagement.CreateWebServicesKeyNoExpiry(User."User Security ID");
            until User.Next() = 0;
    end;
}
```

I'm afraid this will not work when using a Sandbox provided by Microsoft in the Cloud. Upgraded tenants could have the possibility to manual create a Web Services Access Key, but this is already deprecated for Cloud and wil surely be removed in the future. For On-Prem the Web Services Access Key wil continue to work.

**Comment by lvanvugt** [comment]
Wow, @Arthurvdv , that's great. Didn't find time myself to get to work on it. Will go and try it asap.

**Comment by lvanvugt** [comment]
Works like a charm. Tested it just now.

@Arthurvdv do you mind me, with reference to you, to write a blog post on it, or would you rather want to be the one?

**Comment by Arthurvdv** [comment]
The more people are aware of this solution, the more our BC community can grow. I would find it awesome if you would write a blog about is (and be honored with a reference :-))

**Comment by lvanvugt** [comment]
Currently facing 4 out of 6 API tests failing in ADO pipeline.

![image](https://user-images.githubusercontent.com/18466198/170040944-9a549054-410f-4dca-bec9-9797ef04ddd0.png)

Need to study the test run and as such had to enable `createSqlBackup` parameter on `ALOpsDockerRemove` pipeline task.

**Comment by Arthurvdv** [comment]
If I'm remember correctly, the test should be run by test runner ```Test Runner - Isol. Disabled (130451)```. We cannot make use of test isolation (unfortunately).

How did you handle the Test Isolation? In your ALOps steps it seems it uses the default (=test isolation) mode?

```YAML
- task: ALOpsAppTest@1
  displayName: 'ALOPS - Run TestSuite'
  inputs:
    usedocker: true
    import_testtoolkit: false
    import_action: 'Skip'
    testpage: '130455'
    extensionid: '7a6433f5-95fa-46b9-9f91-5c0c3fe3f86f'
    failed_test_action: 'Ignore'
  continueOnError: true
```

An other approach could be to let the Test-App create a Test Suite and refer in ALOps to the specific Test Suite. 


```AL
codeunit 80000 "TST Test Install"
{
    Subtype = Install;

    trigger OnInstallAppPerCompany()
    begin
        SetupTestSuite();
    end;

    local procedure SetupTestSuite()
    var
        ALTestSuite: Record "AL Test Suite";
        TestSuiteMgt: Codeunit "Test Suite Mgt.";
        SuiteName: Code[10];
    begin
        SuiteName := 'API';

        if ALTestSuite.Get(SuiteName) then
            ALTestSuite.Delete(true);

        TestSuiteMgt.CreateTestSuite(SuiteName);
        ALTestSuite.Get(SuiteName);

        TestSuiteMgt.SelectTestMethodsByRange(ALTestSuite, '80000..89999');
        TestSuiteMgt.ChangeTestRunner(ALTestSuite, 130451);
    end;
}
```

```YAML
- task: ALOpsAppTest@1
  displayName: 'ALOPS - Run TestSuite'
  inputs:
    usedocker: true
    testpage: '130455'
    testsuite: 'API'
    failed_test_action: 'Ignore'
  continueOnError: true
```

**Comment by lvanvugt** [comment]
Thanx @Arthurvdv.
Indeed the test runner with _test isolation_ **disabled** (130451 - Test Runner - Isol. Disabled) should be selected. The errors I did get were different form the once I used to get when test isolation was **not** disabled.
Will go and get it working like you suggest, although I do not really fancy this approach. Have therefore suggested an addition to `ALOpsAppTest` (see link just above this comment).

**Comment by lvanvugt** [comment]
Each four failing tests gives same error in pipeline (even with test runner (130451 - Test Runner - Isol. Disabled):
> Assert.Fail failed. GET request failed. Response code is 503 (ServiceUnavailable), expected code is 200. A call to System.Net.HttpWebRequest.GetResponse failed with this message: The remote server returned an error: (503) Server Unavailable.

(see also screen [here](https://github.com/PacktPublishing/Automated-Testing-in-Microsoft-Dynamics-365-Business-Central-Second-Edition/issues/16#issuecomment-1135895165))

As the error is saying it seems to be unable to connect to the API (service).

If I take the backup form the pipeline and restore it it all works fine.

**Comment by lvanvugt** [comment]
Investigated further:

1. Got the pipeline **not** removing the docker container
2. Connected to the web client using URL listed in the `ALOpsDockerWait` log
3. Ran test in AL Test Tool again and got same error
4. Inspected the Service Tier with `Get-NAVServerConfiguration BC` (using `docker exec -it <container name>powershell` to open PowerShell in container) and saw that `ODataServicesEnabled` was **true**, but `ApiServicesEnabled` was **false**

This clearly explains the errors the tests were throwing.

**Comment by lvanvugt** [comment]
Setting `ApiServicesEnabled` to **true** indeed made the tests run successfully.
Now the issue is how to get this turned on when ALOps is creating the container. Well, this way:
```
- task: ALOpsDockerStart@1
  displayName: 'ALOPS - Start Docker Container' # No need to provide any details - it will get the details from previous step
  inputs:
    enable_api_services: true
```

**Comment by lvanvugt** [comment]
![image](https://user-images.githubusercontent.com/18466198/170224701-ca6bc8ed-1088-4be9-ad2c-566cf82317ae.png)

**Comment by Arthurvdv** [comment]
Awesome!

**Comment by lvanvugt** [comment]
Ran into another issue in ALOps: https://github.com/HodorNV/ALOps/issues/520.

**Comment by lvanvugt** [comment]
Have tackled it, for time being, be changing the order of the `ALOpsAppTest` tasks. Now tests are executed well, but the test results are not yet combined into one TestResults.xml that is fed back to the build portal. 
As you can see [here](https://dev.azure.com/PacktPublishing/Automated-Testing-in-Microsoft-Dynamics-365-Business-Central-2Ed/_build/results?buildId=1030&view=ms.vss-test-web.build-test-results-tab) 121 successful tests are reported and these are only from the 2nd test task. It does not include the 6 tests from the 1st test task.

**Comment by lvanvugt** [comment]
OK, closing now with my blog post on this: [Addendum #03 – Simplifying API testing using basic authentication](https://www.fluxxus.nl/index.php/bc/addendum-03-simplifying-api-testing-using-basic-authentication/).

**Comment by rumon10** [comment]
Hello @lvanvugt
I have removed all users and users deleted data from my business central database. After that I have run my APIs test automation program - seeing it asking for authentication (Business central running in Windows authentication)

After Investigating I can see problem in Url and This Url has been generated using GetUrl() method of Business Central.

GetUrl method generated following URL and it ask for authentication
"http://lap032.XXXXXXX.com.bd.local:9048/BC21TEST/api/52Leasing/core/v2.0/companies(08b56f6f-e73a-ed11-bbaa-6045bd8e5663)/"

BUT If change the URL to "http://localhost:9048/BC21TEST/api/52Leasing/core/v2.0/companies(08b56f6f-e73a-ed11-bbaa-6045bd8e5663)/" then it never ask for authentication.

Same Issue happen if I generate URL using "CreateTargetURL" method of LibraryGraphMgt Codeunit.

Could you tell me from where it getting "lap032.XXXXXXX.com.bd.local" (instead of localhost). Is there any setup in Business central to change this name.

**Comment by rumon10** [comment]
I got, actually it is getting from NavServerConfiguration.
But for url generation we should use GetUrl Because "CreateTargetURL" method of LibraryGraphMgt Codeunit has an issue.

**Comment by lvanvugt** [comment]
@rumon10, reading your comments only now as I just returned from vacation. Didn't you read the addenbdum I wrote on my blog to make it easier?

See above:

> OK, closing now with my blog post on this: [Addendum #03 – Simplifying API testing using basic authentication](https://www.fluxxus.nl/index.php/bc/addendum-03-simplifying-api-testing-using-basic-authentication/).
