### ISSUE TITLE
Include Lookup Value in Copy Sales Doc. Feature

### ISSUE THREAD

**Issue by lvanvugt** [PacktPublishing/Automated-Testing-in-Microsoft-Dynamics-365-Business-Central-Second-Edition#2]
When copying a sales document using the **Copy Document** feature the _Lookup Value Code_ field should be inherited from _source Sales Header_ to _target Sales Header_.

 - reported by maarten@magium.nl

**Comment by lvanvugt** [comment]
It has been added to the _Customer wish_ in the book, but not yet implemented.

**Comment by shruthis-shetty** [comment]
> It has been added to the _Customer wish_ in the book, but not yet implemented.

Hi @lvanvugt,
Is that implemented now?

**Comment by lvanvugt** [comment]
@shruthis-shetty this is WIP. Realize that this repo has just been setup as part of the 2nd edition of the book that's being worked on. Anything I am putting in right here is part of that. So, please do not bother.

**Comment by shruthis-shetty** [comment]
Hello @lvanvugt ,
Cool, thanks for the reply.

**Comment by lvanvugt** [comment]
Resolved. Thanx for reporting @mhenricus.

**Comment by lvanvugt** [comment]
Thanx for designing and coding the tests, @julesjagers
